# Cadre général {#intro}

Ce document constitue un guide de bonnes pratiques et d'utilisation des outils développés dans le cadre du Réseau de Suivi de la Température des Milieux Aquatiques du Jura (RSTMAJ). Il a pour vocation d'apporter les informations nécessaires à l'utilisateur en vue d'un travail fiable et facilité pour celui-ci, ainsi que pour l'incorporation des données récoltées à la base de données départementale gérée par la Fédération du Jura pour la Pêche et la Protection des Milieux Aquatiques (FJPPMA) et leur valorisation.

La version la plus à jour de ce document est visible à l'adresse https://jbfagotfede39.github.io/notice-thermie/.

Il est accompagné de fichiers "modèles" afin de constituer une "boîte à outils", disponibles à l'adresse suivante : https://github.com/jbfagotfede39/notice-thermie/raw/master/data/. Les fonctions de traitement utilisées sous R sont disponibles et regroupés au sein du package aquatools : https://github.com/jbfagotfede39/aquatools.

En cas de question(s) ou de remarque(s), merci d'écrire à
[jean-baptiste.fagot@peche-jura.com](mailto:jean-baptiste.fagot@peche-jura.com?subject=[RSTMAJ]%20Boite%20à%20outils).
